# Daily workflow for deploying the documentation to GitHub pages.

name: Deployment

on:
  push:
    branches:
      - main
      
  schedule:
    - cron:  '00 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: pip -q install mkdocs mkdocs-windmill mkdocs-material

      - name: Run build script
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: sh build.sh
